use windows::Win32::UI::Input::KeyboardAndMouse::*;

#[derive(Debug)]
pub enum Key {
  Backspace,
  Tab,
  Enter,
  Shift,
  Ctrl,
  Alt,
  Pause,
  CapsLock,
  Esc,
  Space,
  PageUp,
  PageDown,
  End,
  Home,
  LeftArrow,
  UpArrow,
  RightArrow,
  DownArrow,
  Insert,
  Delete,
  Num0,
  Num1,
  Num2,
  Num3,
  Num4,
  Num5,
  Num6,
  Num7,
  Num8,
  Num9,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  LeftWin,
  RightWin,
  NumPad0,
  NumPad1,
  NumPad2,
  NumPad3,
  NumPad4,
  NumPad5,
  NumPad6,
  NumPad7,
  NumPad8,
  NumPad9,
  Multiply,
  Add,
  Separator,
  Subtract,
  Decimal,
  Divide,
  F1,
  F2,
  F3,
  F4,
  F5,
  F6,
  F7,
  F8,
  F9,
  F10,
  F11,
  F12,
  F13,
  F14,
  F15,
  F16,
  F17,
  F18,
  F19,
  F20,
  F21,
  F22,
  F23,
  F24,
  NumLock,
  ScrollLock,
  LeftShift,
  RightShift,
  LeftCtrl,
  RightCtrl,
  LeftAlt,
  RightAlt,
  PrintScreen,
  VolumeUp,
  VolumeDown,
  VolumeMute,
  MediaNextTrack,
  MediaPrevTrack,
  MediaStop,
  MediaPlayPause,
  OemSemicolon,
  OemQuestion,
  OemTilde,
  OemOpenBrackets,
  OemPipe,
  OemCloseBrackets,
  OemQuotes,
  OemPlus,
  OemComma,
  OemMinus,
  OemPeriod,
  Unknown,
}

impl From<VIRTUAL_KEY> for Key {
  fn from(vk: VIRTUAL_KEY) -> Self {
    match vk {
      VK_BACK => Key::Backspace,
      VK_TAB => Key::Tab,
      VK_RETURN => Key::Enter,
      VK_SHIFT => Key::Shift,
      VK_CONTROL => Key::Ctrl,
      VK_MENU => Key::Alt,
      VK_PAUSE => Key::Pause,
      VK_CAPITAL => Key::CapsLock,
      VK_ESCAPE => Key::Esc,
      VK_SPACE => Key::Space,
      VK_PRIOR => Key::PageUp,
      VK_NEXT => Key::PageDown,
      VK_END => Key::End,
      VK_HOME => Key::Home,
      VK_LEFT => Key::LeftArrow,
      VK_UP => Key::UpArrow,
      VK_RIGHT => Key::RightArrow,
      VK_DOWN => Key::DownArrow,
      VK_INSERT => Key::Insert,
      VK_DELETE => Key::Delete,
      VK_0 => Key::Num0,
      VK_1 => Key::Num1,
      VK_2 => Key::Num2,
      VK_3 => Key::Num3,
      VK_4 => Key::Num4,
      VK_5 => Key::Num5,
      VK_6 => Key::Num6,
      VK_7 => Key::Num7,
      VK_8 => Key::Num8,
      VK_9 => Key::Num9,
      VK_A => Key::A,
      VK_B => Key::B,
      VK_C => Key::C,
      VK_D => Key::D,
      VK_E => Key::E,
      VK_F => Key::F,
      VK_G => Key::G,
      VK_H => Key::H,
      VK_I => Key::I,
      VK_J => Key::J,
      VK_K => Key::K,
      VK_L => Key::L,
      VK_M => Key::M,
      VK_N => Key::N,
      VK_O => Key::O,
      VK_P => Key::P,
      VK_Q => Key::Q,
      VK_R => Key::R,
      VK_S => Key::S,
      VK_T => Key::T,
      VK_U => Key::U,
      VK_V => Key::V,
      VK_W => Key::W,
      VK_X => Key::X,
      VK_Y => Key::Y,
      VK_Z => Key::Z,
      VK_LWIN => Key::LeftWin,
      VK_RWIN => Key::RightWin,
      VK_NUMPAD0 => Key::NumPad0,
      VK_NUMPAD1 => Key::NumPad1,
      VK_NUMPAD2 => Key::NumPad2,
      VK_NUMPAD3 => Key::NumPad3,
      VK_NUMPAD4 => Key::NumPad4,
      VK_NUMPAD5 => Key::NumPad5,
      VK_NUMPAD6 => Key::NumPad6,
      VK_NUMPAD7 => Key::NumPad7,
      VK_NUMPAD8 => Key::NumPad8,
      VK_NUMPAD9 => Key::NumPad9,
      VK_MULTIPLY => Key::Multiply,
      VK_ADD => Key::Add,
      VK_SEPARATOR => Key::Separator,
      VK_SUBTRACT => Key::Subtract,
      VK_DECIMAL => Key::Decimal,
      VK_DIVIDE => Key::Divide,
      VK_F1 => Key::F1,
      VK_F2 => Key::F2,
      VK_F3 => Key::F3,
      VK_F4 => Key::F4,
      VK_F5 => Key::F5,
      VK_F6 => Key::F6,
      VK_F7 => Key::F7,
      VK_F8 => Key::F8,
      VK_F9 => Key::F9,
      VK_F10 => Key::F10,
      VK_F11 => Key::F11,
      VK_F12 => Key::F12,
      VK_F13 => Key::F13,
      VK_F14 => Key::F14,
      VK_F15 => Key::F15,
      VK_F16 => Key::F16,
      VK_F17 => Key::F17,
      VK_F18 => Key::F18,
      VK_F19 => Key::F19,
      VK_F20 => Key::F20,
      VK_F21 => Key::F21,
      VK_F22 => Key::F22,
      VK_F23 => Key::F23,
      VK_F24 => Key::F24,
      VK_NUMLOCK => Key::NumLock,
      VK_SCROLL => Key::ScrollLock,
      VK_LSHIFT => Key::LeftShift,
      VK_RSHIFT => Key::RightShift,
      VK_LCONTROL => Key::LeftCtrl,
      VK_RCONTROL => Key::RightCtrl,
      VK_LMENU => Key::LeftAlt,
      VK_RMENU => Key::RightAlt,
      VK_SNAPSHOT => Key::PrintScreen,
      VK_VOLUME_UP => Key::VolumeUp,
      VK_VOLUME_DOWN => Key::VolumeDown,
      VK_VOLUME_MUTE => Key::VolumeMute,
      VK_MEDIA_NEXT_TRACK => Key::MediaNextTrack,
      VK_MEDIA_PREV_TRACK => Key::MediaPrevTrack,
      VK_MEDIA_STOP => Key::MediaStop,
      VK_MEDIA_PLAY_PAUSE => Key::MediaPlayPause,
      VK_OEM_1 => Key::OemSemicolon,
      VK_OEM_2 => Key::OemQuestion,
      VK_OEM_3 => Key::OemTilde,
      VK_OEM_4 => Key::OemOpenBrackets,
      VK_OEM_5 => Key::OemPipe,
      VK_OEM_6 => Key::OemCloseBrackets,
      VK_OEM_7 => Key::OemQuotes,
      VK_OEM_PLUS => Key::OemPlus,
      VK_OEM_COMMA => Key::OemComma,
      VK_OEM_MINUS => Key::OemMinus,
      VK_OEM_PERIOD => Key::OemPeriod,
      _ => Key::Unknown,
    }
  }
}

impl From<Key> for VIRTUAL_KEY {
  fn from(key: Key) -> Self {
    match key {
      Key::Backspace => VK_BACK,
      Key::Tab => VK_TAB,
      Key::Enter => VK_RETURN,
      Key::Shift => VK_SHIFT,
      Key::Ctrl => VK_CONTROL,
      Key::Alt => VK_MENU,
      Key::Pause => VK_PAUSE,
      Key::CapsLock => VK_CAPITAL,
      Key::Esc => VK_ESCAPE,
      Key::Space => VK_SPACE,
      Key::PageUp => VK_PRIOR,
      Key::PageDown => VK_NEXT,
      Key::End => VK_END,
      Key::Home => VK_HOME,
      Key::LeftArrow => VK_LEFT,
      Key::UpArrow => VK_UP,
      Key::RightArrow => VK_RIGHT,
      Key::DownArrow => VK_DOWN,
      Key::Insert => VK_INSERT,
      Key::Delete => VK_DELETE,
      Key::Num0 => VK_0,
      Key::Num1 => VK_1,
      Key::Num2 => VK_2,
      Key::Num3 => VK_3,
      Key::Num4 => VK_4,
      Key::Num5 => VK_5,
      Key::Num6 => VK_6,
      Key::Num7 => VK_7,
      Key::Num8 => VK_8,
      Key::Num9 => VK_9,
      Key::A => VK_A,
      Key::B => VK_B,
      Key::C => VK_C,
      Key::D => VK_D,
      Key::E => VK_E,
      Key::F => VK_F,
      Key::G => VK_G,
      Key::H => VK_H,
      Key::I => VK_I,
      Key::J => VK_J,
      Key::K => VK_K,
      Key::L => VK_L,
      Key::M => VK_M,
      Key::N => VK_N,
      Key::O => VK_O,
      Key::P => VK_P,
      Key::Q => VK_Q,
      Key::R => VK_R,
      Key::S => VK_S,
      Key::T => VK_T,
      Key::U => VK_U,
      Key::V => VK_V,
      Key::W => VK_W,
      Key::X => VK_X,
      Key::Y => VK_Y,
      Key::Z => VK_Z,
      Key::LeftWin => VK_LWIN,
      Key::RightWin => VK_RWIN,
      Key::NumPad0 => VK_NUMPAD0,
      Key::NumPad1 => VK_NUMPAD1,
      Key::NumPad2 => VK_NUMPAD2,
      Key::NumPad3 => VK_NUMPAD3,
      Key::NumPad4 => VK_NUMPAD4,
      Key::NumPad5 => VK_NUMPAD5,
      Key::NumPad6 => VK_NUMPAD6,
      Key::NumPad7 => VK_NUMPAD7,
      Key::NumPad8 => VK_NUMPAD8,
      Key::NumPad9 => VK_NUMPAD9,
      Key::Multiply => VK_MULTIPLY,
      Key::Add => VK_ADD,
      Key::Separator => VK_SEPARATOR,
      Key::Subtract => VK_SUBTRACT,
      Key::Decimal => VK_DECIMAL,
      Key::Divide => VK_DIVIDE,
      Key::F1 => VK_F1,
      Key::F2 => VK_F2,
      Key::F3 => VK_F3,
      Key::F4 => VK_F4,
      Key::F5 => VK_F5,
      Key::F6 => VK_F6,
      Key::F7 => VK_F7,
      Key::F8 => VK_F8,
      Key::F9 => VK_F9,
      Key::F10 => VK_F10,
      Key::F11 => VK_F11,
      Key::F12 => VK_F12,
      Key::F13 => VK_F13,
      Key::F14 => VK_F14,
      Key::F15 => VK_F15,
      Key::F16 => VK_F16,
      Key::F17 => VK_F17,
      Key::F18 => VK_F18,
      Key::F19 => VK_F19,
      Key::F20 => VK_F20,
      Key::F21 => VK_F21,
      Key::F22 => VK_F22,
      Key::F23 => VK_F23,
      Key::F24 => VK_F24,
      Key::NumLock => VK_NUMLOCK,
      Key::ScrollLock => VK_SCROLL,
      Key::LeftShift => VK_LSHIFT,
      Key::RightShift => VK_RSHIFT,
      Key::LeftCtrl => VK_LCONTROL,
      Key::RightCtrl => VK_RCONTROL,
      Key::LeftAlt => VK_LMENU,
      Key::RightAlt => VK_RMENU,
      Key::PrintScreen => VK_SNAPSHOT,
      Key::VolumeUp => VK_VOLUME_UP,
      Key::VolumeDown => VK_VOLUME_DOWN,
      Key::VolumeMute => VK_VOLUME_MUTE,
      Key::MediaNextTrack => VK_MEDIA_NEXT_TRACK,
      Key::MediaPrevTrack => VK_MEDIA_PREV_TRACK,
      Key::MediaStop => VK_MEDIA_STOP,
      Key::MediaPlayPause => VK_MEDIA_PLAY_PAUSE,
      Key::OemSemicolon => VK_OEM_1,
      Key::OemQuestion => VK_OEM_2,
      Key::OemTilde => VK_OEM_3,
      Key::OemOpenBrackets => VK_OEM_4,
      Key::OemPipe => VK_OEM_5,
      Key::OemCloseBrackets => VK_OEM_6,
      Key::OemQuotes => VK_OEM_7,
      Key::OemPlus => VK_OEM_PLUS,
      Key::OemComma => VK_OEM_COMMA,
      Key::OemMinus => VK_OEM_MINUS,
      Key::OemPeriod => VK_OEM_PERIOD,
      Key::Unknown => VIRTUAL_KEY(0),
    }
  }
}
impl From<String> for Key {
  fn from(key: String) -> Self {
    match key.to_lowercase().as_str() {
      "a" => Key::A,
      "b" => Key::B,
      "c" => Key::C,
      "d" => Key::D,
      "e" => Key::E,
      "f" => Key::F,
      "g" => Key::G,
      "h" => Key::H,
      "i" => Key::I,
      "j" => Key::J,
      "k" => Key::K,
      "l" => Key::L,
      "m" => Key::M,
      "n" => Key::N,
      "o" => Key::O,
      "p" => Key::P,
      "q" => Key::Q,
      "r" => Key::R,
      "s" => Key::S,
      "t" => Key::T,
      "u" => Key::U,
      "v" => Key::V,
      "w" => Key::W,
      "x" => Key::X,
      "y" => Key::Y,
      "z" => Key::Z,
      "0" | "d0" => Key::Num0,
      "1" | "d1" => Key::Num1,
      "2" | "d2" => Key::Num2,
      "3" | "d3" => Key::Num3,
      "4" | "d4" => Key::Num4,
      "5" | "d5" => Key::Num5,
      "6" | "d6" => Key::Num6,
      "7" | "d7" => Key::Num7,
      "8" | "d8" => Key::Num8,
      "9" | "d9" => Key::Num9,
      "numpad0" => Key::NumPad0,
      "numpad1" => Key::NumPad1,
      "numpad2" => Key::NumPad2,
      "numpad3" => Key::NumPad3,
      "numpad4" => Key::NumPad4,
      "numpad5" => Key::NumPad5,
      "numpad6" => Key::NumPad6,
      "numpad7" => Key::NumPad7,
      "numpad8" => Key::NumPad8,
      "numpad9" => Key::NumPad9,
      "f1" => Key::F1,
      "f2" => Key::F2,
      "f3" => Key::F3,
      "f4" => Key::F4,
      "f5" => Key::F5,
      "f6" => Key::F6,
      "f7" => Key::F7,
      "f8" => Key::F8,
      "f9" => Key::F9,
      "f10" => Key::F10,
      "f11" => Key::F11,
      "f12" => Key::F12,
      "f13" => Key::F13,
      "f14" => Key::F14,
      "f15" => Key::F15,
      "f16" => Key::F16,
      "f17" => Key::F17,
      "f18" => Key::F18,
      "f19" => Key::F19,
      "f20" => Key::F20,
      "f21" => Key::F21,
      "f22" => Key::F22,
      "f23" => Key::F23,
      "f24" => Key::F24,
      "leftshift" | "lshift" => Key::LeftShift,
      "rightshift" | "rshift" => Key::RightShift,
      "leftctrl" | "lctrl" => Key::LeftCtrl,
      "rightctrl" | "rctrl" => Key::RightCtrl,
      "leftalt" | "lalt" => Key::LeftAlt,
      "rightalt" | "ralt" => Key::RightAlt,
      "space" => Key::Space,
      "escape" => Key::Esc,
      "back" => Key::Backspace,
      "tab" => Key::Tab,
      "enter" | "return" => Key::Enter,
      "left" => Key::LeftArrow,
      "right" => Key::RightArrow,
      "up" => Key::UpArrow,
      "down" => Key::DownArrow,
      "numlock" => Key::NumLock,
      "scrolllock" => Key::ScrollLock,
      "capslock" => Key::CapsLock,
      "pageup" => Key::PageUp,
      "pagedown" => Key::PageDown,
      "insert" => Key::Insert,
      "delete" => Key::Delete,
      "end" => Key::End,
      "home" => Key::Home,
      "printscreen" => Key::PrintScreen,
      "multiply" => Key::Multiply,
      "add" => Key::Add,
      "subtract" => Key::Subtract,
      "decimal" => Key::Decimal,
      "divide" => Key::Divide,
      "volumeup" => Key::VolumeUp,
      "volumedown" => Key::VolumeDown,
      "volumemute" => Key::VolumeMute,
      "medianexttrack" => Key::MediaNextTrack,
      "mediaprevtrack" => Key::MediaPrevTrack,
      "mediastop" => Key::MediaStop,
      "mediaplaypause" => Key::MediaPlayPause,
      "oemsemicolon" => Key::OemSemicolon,
      "oemquestion" => Key::OemQuestion,
      "oemtilde" => Key::OemTilde,
      "oemopenbrackets" => Key::OemOpenBrackets,
      "oempipe" => Key::OemPipe,
      "oemclosebrackets" => Key::OemCloseBrackets,
      "oemquotes" => Key::OemQuotes,
      "oemplus" => Key::OemPlus,
      "oemcomma" => Key::OemComma,
      "oemminus" => Key::OemMinus,
      "oemperiod" => Key::OemPeriod,
      _ => Key::Unknown,
    }
  }
}
